before:
  hooks:
    - "go mod tidy"
    - "go test ./..."
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
dockers:
  - image_templates:
      - "francescomari/metrics-generator:{{ .Version }}"
checksum:
  name_template: "checksums.txt"
